# <<< 최종 디버깅 버전 .github/workflows/main.yml >>>

name: Daily Apartment Data Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      ## [가장 중요한 수정] ##
      # 파이썬 스크립트를 실행하기 전에,
      # Actions가 보고 있는 main.py 파일의 내용을 그대로 출력합니다.
      - name: View main.py content
        run: cat main.py

      - name: Run Python script to update data
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GSPREAD_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GSPREAD_SERVICE_ACCOUNT_EMAIL }}
        run: python main.py
