name: Daily Apartment Data Crawl

on:
  schedule:
    # 매일 오전 5시(KST)에 실행 (UTC 기준 20시)
    - cron: '0 20 * * *'
  workflow_dispatch:
    # 수동 실행 버튼 추가

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create Google Credentials file from Secret
      run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json
    - name: Run Python script
      env:
        SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
      run: python main.py
